name: my-test-workflow
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          /usr/bin/python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          python generate_data.py
          python train_model.py
          
          echo "## Model metrics" >> report.md
          cat metrics.txt >> report.md
          # cml comment create report.md

