name: Train Model Workflow

on:
  push:
    branches:
      - dev
  workflow_dispatch:


jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          /usr/bin/python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          python generate_data.py
          python train_model.py
          
          # Post reports as comments in GitHub PRs
          cat metrics.txt >> report.md
          # cml comment create report.md
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Retrained new unsupervised model
      
      # - name: create pull request --
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     commit-message: Auto Pull Request
      #     title: Your desired title
      #     body: Auto-created Pull Request
      #     branch: dev
      
